Chandler Stone / One Month Submission
UAH-ACM/website pull request #49
Opened 2023-10-11 00:00 UTC by chandler-stone

# Pull Request Name / Title
Let us know what added/removed/changed here. Make sure that you have completed the PR Checklist below before you open the PR publicly.

# Category
- [X] One-Month Project Submission
- [ ] Bug Fix

# PR Checklist
Complete this checklist before opening your pull request
- [ ] If the PR is a bug fix, the issue is linked in the PR Content
- [X] If this PR is a One-Month submission, include if you want your site to be listed publicly on our website.
- [ ] If this PR is a work in progress, it's name starts with `WIP:`. Example: `WIP: Nathan Solomon One-Month Submission`

2023-10-16 22:55 UTC, salsajeries commented
ACM Logo link needs to be changed to "ACM Chapter" logo. We aren't allowed to use the ACM logo :((

2023-10-16 22:57 UTC, earocorn commented
See Salwa

2023-10-16 22:59 UTC, salsajeries requested changes
ACM Logo link needs to be changed to "ACM Chapter" logo. We aren't allowed to use the ACM logo :((

2023-10-16 23:00 UTC, shorewind commented on members/ChandlerStone/index.html
> +        <p>Hello! I am Chandler Stone, an underagraduate studying computer engineering here at the University of Alabama in Huntsville!
undergraduate*

2023-10-18 23:48 UTC, chandler-stone commented
Fixed wrong logo issue.
Fixed undergraduate misspelling issue.
Logo sizes were increased so "chapter" on the ACM chapter logo is clearly visual.

2023-10-19 21:59 UTC, salsajeries approved these changes
Changes look good!

2023-10-19 21:59 UTC, merged